// Node uniqueness constraints — one per label, generated by GraphStore.setup_schema().
// Uses portable REQUIRE … IS UNIQUE syntax (compatible with Community and Enterprise).
// Upgrade to IS NODE KEY if deployment is confirmed Enterprise/Aura.
CREATE CONSTRAINT ${Label}_id IF NOT EXISTS FOR (n:${Label}) REQUIRE n.id IS UNIQUE;
