# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
import baml_py

from . import stream_types, types, type_builder
from .parser import LlmResponseParser, LlmStreamParser
from .runtime import DoNotUseDirectlyCallManager, BamlCallOptions
from .globals import DO_NOT_USE_DIRECTLY_UNLESS_YOU_KNOW_WHAT_YOURE_DOING_RUNTIME as __runtime__


class BamlAsyncClient:
    __options: DoNotUseDirectlyCallManager
    __stream_client: "BamlStreamClient"
    __http_request: "BamlHttpRequestClient"
    __http_stream_request: "BamlHttpStreamRequestClient"
    __llm_response_parser: LlmResponseParser
    __llm_stream_parser: LlmStreamParser

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options
        self.__stream_client = BamlStreamClient(options)
        self.__http_request = BamlHttpRequestClient(options)
        self.__http_stream_request = BamlHttpStreamRequestClient(options)
        self.__llm_response_parser = LlmResponseParser(options)
        self.__llm_stream_parser = LlmStreamParser(options)

    def with_options(self,
        tb: typing.Optional[type_builder.TypeBuilder] = None,
        client_registry: typing.Optional[baml_py.baml_py.ClientRegistry] = None,
        client: typing.Optional[str] = None,
        collector: typing.Optional[typing.Union[baml_py.baml_py.Collector, typing.List[baml_py.baml_py.Collector]]] = None,
        env: typing.Optional[typing.Dict[str, typing.Optional[str]]] = None,
        tags: typing.Optional[typing.Dict[str, str]] = None,
        on_tick: typing.Optional[typing.Callable[[str, baml_py.baml_py.FunctionLog], None]] = None,
    ) -> "BamlAsyncClient":
        options: BamlCallOptions = {}
        if tb is not None:
            options["tb"] = tb
        if client_registry is not None:
            options["client_registry"] = client_registry
        if client is not None:
            options["client"] = client
        if collector is not None:
            options["collector"] = collector
        if env is not None:
            options["env"] = env
        if tags is not None:
            options["tags"] = tags
        if on_tick is not None:
            options["on_tick"] = on_tick
        return BamlAsyncClient(self.__options.merge_options(options))

    @property
    def stream(self):
      return self.__stream_client

    @property
    def request(self):
      return self.__http_request

    @property
    def stream_request(self):
      return self.__http_stream_request

    @property
    def parse(self):
      return self.__llm_response_parser

    @property
    def parse_stream(self):
      return self.__llm_stream_parser

    async def AreEntityMentionsSame(self, entityA: str,typeA: str,entityB: str,typeB: str,
        baml_options: BamlCallOptions = {},
    ) -> types.SamenessVerdict:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            # Use streaming internally when on_tick is provided
            __stream__ = self.stream.AreEntityMentionsSame(entityA=entityA,typeA=typeA,entityB=entityB,typeB=typeB,
                baml_options=baml_options)
            return await __stream__.get_final_response()
        else:
            # Original non-streaming code
            __result__ = await self.__options.merge_options(baml_options).call_function_async(function_name="AreEntityMentionsSame", args={
                "entityA": entityA,"typeA": typeA,"entityB": entityB,"typeB": typeB,
            })
            return typing.cast(types.SamenessVerdict, __result__.cast_to(types, types, stream_types, False, __runtime__))
    async def ExtractKnowledgeGraph(self, text: str,source_type: str,
        baml_options: BamlCallOptions = {},
    ) -> types.ExtractedKnowledgeGraph:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            # Use streaming internally when on_tick is provided
            __stream__ = self.stream.ExtractKnowledgeGraph(text=text,source_type=source_type,
                baml_options=baml_options)
            return await __stream__.get_final_response()
        else:
            # Original non-streaming code
            __result__ = await self.__options.merge_options(baml_options).call_function_async(function_name="ExtractKnowledgeGraph", args={
                "text": text,"source_type": source_type,
            })
            return typing.cast(types.ExtractedKnowledgeGraph, __result__.cast_to(types, types, stream_types, False, __runtime__))
    async def ExtractResume(self, resume: str,
        baml_options: BamlCallOptions = {},
    ) -> types.Resume:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            # Use streaming internally when on_tick is provided
            __stream__ = self.stream.ExtractResume(resume=resume,
                baml_options=baml_options)
            return await __stream__.get_final_response()
        else:
            # Original non-streaming code
            __result__ = await self.__options.merge_options(baml_options).call_function_async(function_name="ExtractResume", args={
                "resume": resume,
            })
            return typing.cast(types.Resume, __result__.cast_to(types, types, stream_types, False, __runtime__))
    async def GenerateCommunityReport(self, context_data: str,schema_context: str,max_report_length: int,
        baml_options: BamlCallOptions = {},
    ) -> types.CommunityReportOutput:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            # Use streaming internally when on_tick is provided
            __stream__ = self.stream.GenerateCommunityReport(context_data=context_data,schema_context=schema_context,max_report_length=max_report_length,
                baml_options=baml_options)
            return await __stream__.get_final_response()
        else:
            # Original non-streaming code
            __result__ = await self.__options.merge_options(baml_options).call_function_async(function_name="GenerateCommunityReport", args={
                "context_data": context_data,"schema_context": schema_context,"max_report_length": max_report_length,
            })
            return typing.cast(types.CommunityReportOutput, __result__.cast_to(types, types, stream_types, False, __runtime__))
    async def GenerateCypherQuery(self, question: str,schema_description: str,examples: str,
        baml_options: BamlCallOptions = {},
    ) -> types.CypherQuery:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            # Use streaming internally when on_tick is provided
            __stream__ = self.stream.GenerateCypherQuery(question=question,schema_description=schema_description,examples=examples,
                baml_options=baml_options)
            return await __stream__.get_final_response()
        else:
            # Original non-streaming code
            __result__ = await self.__options.merge_options(baml_options).call_function_async(function_name="GenerateCypherQuery", args={
                "question": question,"schema_description": schema_description,"examples": examples,
            })
            return typing.cast(types.CypherQuery, __result__.cast_to(types, types, stream_types, False, __runtime__))
    async def IdentifyClusterDuplicates(self, item: str,itemKind: str,candidateSet: typing.List[str],
        baml_options: BamlCallOptions = {},
    ) -> types.ClusterDeduplicationVerdict:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            # Use streaming internally when on_tick is provided
            __stream__ = self.stream.IdentifyClusterDuplicates(item=item,itemKind=itemKind,candidateSet=candidateSet,
                baml_options=baml_options)
            return await __stream__.get_final_response()
        else:
            # Original non-streaming code
            __result__ = await self.__options.merge_options(baml_options).call_function_async(function_name="IdentifyClusterDuplicates", args={
                "item": item,"itemKind": itemKind,"candidateSet": candidateSet,
            })
            return typing.cast(types.ClusterDeduplicationVerdict, __result__.cast_to(types, types, stream_types, False, __runtime__))
    async def MapCommunityBatch(self, context_data: str,query: str,
        baml_options: BamlCallOptions = {},
    ) -> types.MapResponse:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            # Use streaming internally when on_tick is provided
            __stream__ = self.stream.MapCommunityBatch(context_data=context_data,query=query,
                baml_options=baml_options)
            return await __stream__.get_final_response()
        else:
            # Original non-streaming code
            __result__ = await self.__options.merge_options(baml_options).call_function_async(function_name="MapCommunityBatch", args={
                "context_data": context_data,"query": query,
            })
            return typing.cast(types.MapResponse, __result__.cast_to(types, types, stream_types, False, __runtime__))
    async def ReduceMapResponses(self, map_responses: str,query: str,
        baml_options: BamlCallOptions = {},
    ) -> types.ReduceAnswer:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            # Use streaming internally when on_tick is provided
            __stream__ = self.stream.ReduceMapResponses(map_responses=map_responses,query=query,
                baml_options=baml_options)
            return await __stream__.get_final_response()
        else:
            # Original non-streaming code
            __result__ = await self.__options.merge_options(baml_options).call_function_async(function_name="ReduceMapResponses", args={
                "map_responses": map_responses,"query": query,
            })
            return typing.cast(types.ReduceAnswer, __result__.cast_to(types, types, stream_types, False, __runtime__))
    


class BamlStreamClient:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    def AreEntityMentionsSame(self, entityA: str,typeA: str,entityB: str,typeB: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlStream[stream_types.SamenessVerdict, types.SamenessVerdict]:
        __ctx__, __result__ = self.__options.merge_options(baml_options).create_async_stream(function_name="AreEntityMentionsSame", args={
            "entityA": entityA,"typeA": typeA,"entityB": entityB,"typeB": typeB,
        })
        return baml_py.BamlStream[stream_types.SamenessVerdict, types.SamenessVerdict](
          __result__,
          lambda x: typing.cast(stream_types.SamenessVerdict, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.SamenessVerdict, x.cast_to(types, types, stream_types, False, __runtime__)),
          __ctx__,
        )
    def ExtractKnowledgeGraph(self, text: str,source_type: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlStream[stream_types.ExtractedKnowledgeGraph, types.ExtractedKnowledgeGraph]:
        __ctx__, __result__ = self.__options.merge_options(baml_options).create_async_stream(function_name="ExtractKnowledgeGraph", args={
            "text": text,"source_type": source_type,
        })
        return baml_py.BamlStream[stream_types.ExtractedKnowledgeGraph, types.ExtractedKnowledgeGraph](
          __result__,
          lambda x: typing.cast(stream_types.ExtractedKnowledgeGraph, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.ExtractedKnowledgeGraph, x.cast_to(types, types, stream_types, False, __runtime__)),
          __ctx__,
        )
    def ExtractResume(self, resume: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlStream[stream_types.Resume, types.Resume]:
        __ctx__, __result__ = self.__options.merge_options(baml_options).create_async_stream(function_name="ExtractResume", args={
            "resume": resume,
        })
        return baml_py.BamlStream[stream_types.Resume, types.Resume](
          __result__,
          lambda x: typing.cast(stream_types.Resume, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.Resume, x.cast_to(types, types, stream_types, False, __runtime__)),
          __ctx__,
        )
    def GenerateCommunityReport(self, context_data: str,schema_context: str,max_report_length: int,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlStream[stream_types.CommunityReportOutput, types.CommunityReportOutput]:
        __ctx__, __result__ = self.__options.merge_options(baml_options).create_async_stream(function_name="GenerateCommunityReport", args={
            "context_data": context_data,"schema_context": schema_context,"max_report_length": max_report_length,
        })
        return baml_py.BamlStream[stream_types.CommunityReportOutput, types.CommunityReportOutput](
          __result__,
          lambda x: typing.cast(stream_types.CommunityReportOutput, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.CommunityReportOutput, x.cast_to(types, types, stream_types, False, __runtime__)),
          __ctx__,
        )
    def GenerateCypherQuery(self, question: str,schema_description: str,examples: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlStream[stream_types.CypherQuery, types.CypherQuery]:
        __ctx__, __result__ = self.__options.merge_options(baml_options).create_async_stream(function_name="GenerateCypherQuery", args={
            "question": question,"schema_description": schema_description,"examples": examples,
        })
        return baml_py.BamlStream[stream_types.CypherQuery, types.CypherQuery](
          __result__,
          lambda x: typing.cast(stream_types.CypherQuery, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.CypherQuery, x.cast_to(types, types, stream_types, False, __runtime__)),
          __ctx__,
        )
    def IdentifyClusterDuplicates(self, item: str,itemKind: str,candidateSet: typing.List[str],
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlStream[stream_types.ClusterDeduplicationVerdict, types.ClusterDeduplicationVerdict]:
        __ctx__, __result__ = self.__options.merge_options(baml_options).create_async_stream(function_name="IdentifyClusterDuplicates", args={
            "item": item,"itemKind": itemKind,"candidateSet": candidateSet,
        })
        return baml_py.BamlStream[stream_types.ClusterDeduplicationVerdict, types.ClusterDeduplicationVerdict](
          __result__,
          lambda x: typing.cast(stream_types.ClusterDeduplicationVerdict, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.ClusterDeduplicationVerdict, x.cast_to(types, types, stream_types, False, __runtime__)),
          __ctx__,
        )
    def MapCommunityBatch(self, context_data: str,query: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlStream[stream_types.MapResponse, types.MapResponse]:
        __ctx__, __result__ = self.__options.merge_options(baml_options).create_async_stream(function_name="MapCommunityBatch", args={
            "context_data": context_data,"query": query,
        })
        return baml_py.BamlStream[stream_types.MapResponse, types.MapResponse](
          __result__,
          lambda x: typing.cast(stream_types.MapResponse, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.MapResponse, x.cast_to(types, types, stream_types, False, __runtime__)),
          __ctx__,
        )
    def ReduceMapResponses(self, map_responses: str,query: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlStream[stream_types.ReduceAnswer, types.ReduceAnswer]:
        __ctx__, __result__ = self.__options.merge_options(baml_options).create_async_stream(function_name="ReduceMapResponses", args={
            "map_responses": map_responses,"query": query,
        })
        return baml_py.BamlStream[stream_types.ReduceAnswer, types.ReduceAnswer](
          __result__,
          lambda x: typing.cast(stream_types.ReduceAnswer, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.ReduceAnswer, x.cast_to(types, types, stream_types, False, __runtime__)),
          __ctx__,
        )
    

class BamlHttpRequestClient:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    async def AreEntityMentionsSame(self, entityA: str,typeA: str,entityB: str,typeB: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = await self.__options.merge_options(baml_options).create_http_request_async(function_name="AreEntityMentionsSame", args={
            "entityA": entityA,"typeA": typeA,"entityB": entityB,"typeB": typeB,
        }, mode="request")
        return __result__
    async def ExtractKnowledgeGraph(self, text: str,source_type: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = await self.__options.merge_options(baml_options).create_http_request_async(function_name="ExtractKnowledgeGraph", args={
            "text": text,"source_type": source_type,
        }, mode="request")
        return __result__
    async def ExtractResume(self, resume: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = await self.__options.merge_options(baml_options).create_http_request_async(function_name="ExtractResume", args={
            "resume": resume,
        }, mode="request")
        return __result__
    async def GenerateCommunityReport(self, context_data: str,schema_context: str,max_report_length: int,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = await self.__options.merge_options(baml_options).create_http_request_async(function_name="GenerateCommunityReport", args={
            "context_data": context_data,"schema_context": schema_context,"max_report_length": max_report_length,
        }, mode="request")
        return __result__
    async def GenerateCypherQuery(self, question: str,schema_description: str,examples: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = await self.__options.merge_options(baml_options).create_http_request_async(function_name="GenerateCypherQuery", args={
            "question": question,"schema_description": schema_description,"examples": examples,
        }, mode="request")
        return __result__
    async def IdentifyClusterDuplicates(self, item: str,itemKind: str,candidateSet: typing.List[str],
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = await self.__options.merge_options(baml_options).create_http_request_async(function_name="IdentifyClusterDuplicates", args={
            "item": item,"itemKind": itemKind,"candidateSet": candidateSet,
        }, mode="request")
        return __result__
    async def MapCommunityBatch(self, context_data: str,query: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = await self.__options.merge_options(baml_options).create_http_request_async(function_name="MapCommunityBatch", args={
            "context_data": context_data,"query": query,
        }, mode="request")
        return __result__
    async def ReduceMapResponses(self, map_responses: str,query: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = await self.__options.merge_options(baml_options).create_http_request_async(function_name="ReduceMapResponses", args={
            "map_responses": map_responses,"query": query,
        }, mode="request")
        return __result__
    

class BamlHttpStreamRequestClient:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    async def AreEntityMentionsSame(self, entityA: str,typeA: str,entityB: str,typeB: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = await self.__options.merge_options(baml_options).create_http_request_async(function_name="AreEntityMentionsSame", args={
            "entityA": entityA,"typeA": typeA,"entityB": entityB,"typeB": typeB,
        }, mode="stream")
        return __result__
    async def ExtractKnowledgeGraph(self, text: str,source_type: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = await self.__options.merge_options(baml_options).create_http_request_async(function_name="ExtractKnowledgeGraph", args={
            "text": text,"source_type": source_type,
        }, mode="stream")
        return __result__
    async def ExtractResume(self, resume: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = await self.__options.merge_options(baml_options).create_http_request_async(function_name="ExtractResume", args={
            "resume": resume,
        }, mode="stream")
        return __result__
    async def GenerateCommunityReport(self, context_data: str,schema_context: str,max_report_length: int,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = await self.__options.merge_options(baml_options).create_http_request_async(function_name="GenerateCommunityReport", args={
            "context_data": context_data,"schema_context": schema_context,"max_report_length": max_report_length,
        }, mode="stream")
        return __result__
    async def GenerateCypherQuery(self, question: str,schema_description: str,examples: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = await self.__options.merge_options(baml_options).create_http_request_async(function_name="GenerateCypherQuery", args={
            "question": question,"schema_description": schema_description,"examples": examples,
        }, mode="stream")
        return __result__
    async def IdentifyClusterDuplicates(self, item: str,itemKind: str,candidateSet: typing.List[str],
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = await self.__options.merge_options(baml_options).create_http_request_async(function_name="IdentifyClusterDuplicates", args={
            "item": item,"itemKind": itemKind,"candidateSet": candidateSet,
        }, mode="stream")
        return __result__
    async def MapCommunityBatch(self, context_data: str,query: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = await self.__options.merge_options(baml_options).create_http_request_async(function_name="MapCommunityBatch", args={
            "context_data": context_data,"query": query,
        }, mode="stream")
        return __result__
    async def ReduceMapResponses(self, map_responses: str,query: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = await self.__options.merge_options(baml_options).create_http_request_async(function_name="ReduceMapResponses", args={
            "map_responses": map_responses,"query": query,
        }, mode="stream")
        return __result__
    

b = BamlAsyncClient(DoNotUseDirectlyCallManager({}))