# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions


from . import stream_types, types
from .runtime import DoNotUseDirectlyCallManager, BamlCallOptions

class LlmResponseParser:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    def AreEntityMentionsSame(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.SamenessVerdict:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="AreEntityMentionsSame", llm_response=llm_response, mode="request")
        return typing.cast(types.SamenessVerdict, __result__)

    def ExtractKnowledgeGraph(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.ExtractedKnowledgeGraph:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="ExtractKnowledgeGraph", llm_response=llm_response, mode="request")
        return typing.cast(types.ExtractedKnowledgeGraph, __result__)

    def ExtractResume(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.Resume:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="ExtractResume", llm_response=llm_response, mode="request")
        return typing.cast(types.Resume, __result__)

    def GenerateCommunityReport(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.CommunityReportOutput:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="GenerateCommunityReport", llm_response=llm_response, mode="request")
        return typing.cast(types.CommunityReportOutput, __result__)

    def GenerateCypherQuery(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.CypherQuery:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="GenerateCypherQuery", llm_response=llm_response, mode="request")
        return typing.cast(types.CypherQuery, __result__)

    def IdentifyClusterDuplicates(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.ClusterDeduplicationVerdict:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="IdentifyClusterDuplicates", llm_response=llm_response, mode="request")
        return typing.cast(types.ClusterDeduplicationVerdict, __result__)

    def MapCommunityBatch(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.MapResponse:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="MapCommunityBatch", llm_response=llm_response, mode="request")
        return typing.cast(types.MapResponse, __result__)

    def ReduceMapResponses(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.ReduceAnswer:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="ReduceMapResponses", llm_response=llm_response, mode="request")
        return typing.cast(types.ReduceAnswer, __result__)

    

class LlmStreamParser:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    def AreEntityMentionsSame(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.SamenessVerdict:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="AreEntityMentionsSame", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.SamenessVerdict, __result__)

    def ExtractKnowledgeGraph(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.ExtractedKnowledgeGraph:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="ExtractKnowledgeGraph", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.ExtractedKnowledgeGraph, __result__)

    def ExtractResume(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.Resume:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="ExtractResume", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.Resume, __result__)

    def GenerateCommunityReport(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.CommunityReportOutput:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="GenerateCommunityReport", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.CommunityReportOutput, __result__)

    def GenerateCypherQuery(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.CypherQuery:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="GenerateCypherQuery", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.CypherQuery, __result__)

    def IdentifyClusterDuplicates(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.ClusterDeduplicationVerdict:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="IdentifyClusterDuplicates", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.ClusterDeduplicationVerdict, __result__)

    def MapCommunityBatch(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.MapResponse:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="MapCommunityBatch", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.MapResponse, __result__)

    def ReduceMapResponses(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.ReduceAnswer:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="ReduceMapResponses", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.ReduceAnswer, __result__)

    