# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
from enum import Enum


from pydantic import BaseModel, ConfigDict, Field


import baml_py

CheckT = typing_extensions.TypeVar('CheckT')
CheckName = typing_extensions.TypeVar('CheckName', bound=str)

class Check(BaseModel):
    name: str
    expression: str
    status: str
class Checked(BaseModel, typing.Generic[CheckT, CheckName]):
    value: CheckT
    checks: typing.Dict[CheckName, Check]

def get_checks(checks: typing.Dict[CheckName, Check]) -> typing.List[Check]:
    return list(checks.values())

def all_succeeded(checks: typing.Dict[CheckName, Check]) -> bool:
    return all(check.status == "succeeded" for check in get_checks(checks))
# #########################################################################
# Generated enums (2)
# #########################################################################

class EntityType(str, Enum):
    pass

class RelationType(str, Enum):
    pass

# #########################################################################
# Generated classes (12)
# #########################################################################

class ClusterDeduplicationVerdict(BaseModel):
    duplicates: typing.List[str] = Field(description='Exact matches to items in the candidate set that mean the same thing as the item')
    alias: str = Field(description='Best canonical name representing item + duplicates, ideally chosen from the candidate set (Wikidata-alias style)')
    reasoning: str = Field(description='One sentence: why these are/aren\'t duplicates and why this alias was chosen')

class CommunityReportOutput(BaseModel):
    title: str = Field(description='Short descriptive title for this community.')
    summary: str = Field(description='2-3 sentence summary of the community\'s medical significance.')
    findings: typing.List["Finding"] = Field(description='Key structured findings, ordered by importance.')
    rating: float = Field(description='Importance rating 0.0-10.0 (higher = more clinically important).')
    rating_explanation: str = Field(description='One sentence justifying the rating.')

class CypherQuery(BaseModel):
    cypher: str = Field(description='A valid read-only Cypher MATCH/RETURN query answering the question. No mutations.')
    reasoning: str = Field(description='One sentence: what the query finds and why this structure was chosen')

class ExtractedEntity(BaseModel):
    name: str = Field(description='Canonical name. Use generic/INN for drugs, HGNC symbol for genes.')
    entity_type: typing.Union[EntityType, str] = Field(description='Must be one of the configured entity types.')
    description: typing.Optional[str] = Field(default=None, description='Optional brief description of this entity from the text.')
    aliases: typing.List[str] = Field(description='Abbreviations or synonyms found in text.')
    properties: typing.Dict[str, str] = Field(description='Type-specific properties: e.g. icd10Code for Disease, mechanism for Drug.')
    score: float = Field(description='1.0 = explicitly named, 0.7 = strongly implied, 0.5 = inferred')

class ExtractedKnowledgeGraph(BaseModel):
    entities: typing.List["ExtractedEntity"]
    relations: typing.List["ExtractedRelation"]

class ExtractedRelation(BaseModel):
    head_name: str = Field(description='Canonical name of the head entity — must appear in entities list')
    tail_name: str = Field(description='Canonical name of the tail entity — must appear in entities list')
    relation_type: typing.Union[RelationType, str] = Field(description='Must be one of the configured relation types.')
    score: float
    properties: typing.Dict[str, str] = Field(description='Relation-specific properties.')

class Finding(BaseModel):
    summary: str = Field(description='One-sentence finding headline.')
    explanation: str = Field(description='Supporting evidence and context.')

class MapKeyPoint(BaseModel):
    description: str = Field(description='A key point extracted from the community report batch')
    score: int = Field(description='Importance score 0-100')
    source_report_ids: typing.List[str] = Field(description='IDs of community reports supporting this point')

class MapResponse(BaseModel):
    points: typing.List["MapKeyPoint"]

class ReduceAnswer(BaseModel):
    answer: str = Field(description='Synthesized answer from all analyst reports')
    key_themes: typing.List[str] = Field(description='Major themes identified across communities')
    supporting_reports: typing.List[str] = Field(description='Community report IDs providing evidence')

class Resume(BaseModel):
    name: str
    email: str
    experience: typing.List[str]
    skills: typing.List[str]

class SamenessVerdict(BaseModel):
    areSameEntity: bool
    canonicalName: typing.Optional[str] = Field(default=None, description='If same, the preferred canonical name (generic INN for drugs, HGNC for genes)')
    reasoning: str = Field(description='One sentence: key evidence for or against')

# #########################################################################
# Generated type aliases (0)
# #########################################################################
