# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

from . import types
from . import stream_types


type_map = {

    "types.ClusterDeduplicationVerdict": types.ClusterDeduplicationVerdict,
    "stream_types.ClusterDeduplicationVerdict": stream_types.ClusterDeduplicationVerdict,

    "types.CommunityReportOutput": types.CommunityReportOutput,
    "stream_types.CommunityReportOutput": stream_types.CommunityReportOutput,

    "types.CypherQuery": types.CypherQuery,
    "stream_types.CypherQuery": stream_types.CypherQuery,

    "types.ExtractedEntity": types.ExtractedEntity,
    "stream_types.ExtractedEntity": stream_types.ExtractedEntity,

    "types.ExtractedKnowledgeGraph": types.ExtractedKnowledgeGraph,
    "stream_types.ExtractedKnowledgeGraph": stream_types.ExtractedKnowledgeGraph,

    "types.ExtractedRelation": types.ExtractedRelation,
    "stream_types.ExtractedRelation": stream_types.ExtractedRelation,

    "types.Finding": types.Finding,
    "stream_types.Finding": stream_types.Finding,

    "types.MapKeyPoint": types.MapKeyPoint,
    "stream_types.MapKeyPoint": stream_types.MapKeyPoint,

    "types.MapResponse": types.MapResponse,
    "stream_types.MapResponse": stream_types.MapResponse,

    "types.ReduceAnswer": types.ReduceAnswer,
    "stream_types.ReduceAnswer": stream_types.ReduceAnswer,

    "types.Resume": types.Resume,
    "stream_types.Resume": stream_types.Resume,

    "types.SamenessVerdict": types.SamenessVerdict,
    "stream_types.SamenessVerdict": stream_types.SamenessVerdict,


    "types.EntityType": types.EntityType,

    "types.RelationType": types.RelationType,

}